http:
  routers:
    traefik:
      rule: "Host(`traefik.cryptify.ss-centi.com`)"
      entryPoints:
        - http
      # middlewares:
        # - auth
        # - redirect
      service: api@internal

    traefik-secure:
      rule: "Host(`traefik.cryptify.ss-centi.com`)"
      entryPoints:
        - https
    #   #middlewares:
    #   #
      tls:
        certresolver: http
      service: api@internal
