services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    networks:
      - traefik-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M  
    

networks:
  traefik-proxy:
    external: true

volumes:
  portainer-data:
    external: true
